[package]
name = "usd_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dynamic-weighted-index = "0.1.0"
rand = { version = "0.8.5", features = ["small_rng"] }
incr_stats = "1.0.1"